// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdI86VmLx0Shaoa5mmCn5u-eQZHzIsnps',
    appId: '1:657594258311:web:f0be28669eda81bc8a7922',
    messagingSenderId: '657594258311',
    projectId: 'notes-7eba2',
    authDomain: 'notes-7eba2.firebaseapp.com',
    storageBucket: 'notes-7eba2.appspot.com',
    measurementId: 'G-792CM4NQN7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTrRwdm2ouKCeydNdWF_hzVsJL8ka-X94',
    appId: '1:657594258311:android:d56ca13c4e79d2848a7922',
    messagingSenderId: '657594258311',
    projectId: 'notes-7eba2',
    storageBucket: 'notes-7eba2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfRe-AnPgGuOjcaHLe41WeifnLFhgQPxs',
    appId: '1:657594258311:ios:87ad05dcd6c0663c8a7922',
    messagingSenderId: '657594258311',
    projectId: 'notes-7eba2',
    storageBucket: 'notes-7eba2.appspot.com',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfRe-AnPgGuOjcaHLe41WeifnLFhgQPxs',
    appId: '1:657594258311:ios:87ad05dcd6c0663c8a7922',
    messagingSenderId: '657594258311',
    projectId: 'notes-7eba2',
    storageBucket: 'notes-7eba2.appspot.com',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAdI86VmLx0Shaoa5mmCn5u-eQZHzIsnps',
    appId: '1:657594258311:web:96db19d4176ef2608a7922',
    messagingSenderId: '657594258311',
    projectId: 'notes-7eba2',
    authDomain: 'notes-7eba2.firebaseapp.com',
    storageBucket: 'notes-7eba2.appspot.com',
    measurementId: 'G-LLZZEWTZGE',
  );
}
